<?php
/**
 * KeysApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Authoring API
 *
 * API used to query and manipulate Tweek data in git
 *
 * OpenAPI spec version: 0.2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\Configuration;
use \Swagger\Client\ObjectSerializer;

/**
 * KeysApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KeysApi
{
    /**
     * API Client
     *
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Swagger\Client\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     *
     * @return KeysApi
     */
    public function setApiClient(\Swagger\Client\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation keysDeleteKey
     *
     * @param string $key_path  (required)
     * @param string $author_name  (required)
     * @param string $author_email  (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return string
     */
    public function keysDeleteKey($key_path, $author_name, $author_email)
    {
        list($response) = $this->keysDeleteKeyWithHttpInfo($key_path, $author_name, $author_email);
        return $response;
    }

    /**
     * Operation keysDeleteKeyWithHttpInfo
     *
     * @param string $key_path  (required)
     * @param string $author_name  (required)
     * @param string $author_email  (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function keysDeleteKeyWithHttpInfo($key_path, $author_name, $author_email)
    {
        // verify the required parameter 'key_path' is set
        if ($key_path === null) {
            throw new \InvalidArgumentException('Missing the required parameter $key_path when calling keysDeleteKey');
        }
        // verify the required parameter 'author_name' is set
        if ($author_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $author_name when calling keysDeleteKey');
        }
        // verify the required parameter 'author_email' is set
        if ($author_email === null) {
            throw new \InvalidArgumentException('Missing the required parameter $author_email when calling keysDeleteKey');
        }
        // parse inputs
        $resourcePath = "/key";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['text/html']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($key_path !== null) {
            $queryParams['keyPath'] = $this->apiClient->getSerializer()->toQueryValue($key_path);
        }
        // query params
        if ($author_name !== null) {
            $queryParams['author.name'] = $this->apiClient->getSerializer()->toQueryValue($author_name);
        }
        // query params
        if ($author_email !== null) {
            $queryParams['author.email'] = $this->apiClient->getSerializer()->toQueryValue($author_email);
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                'string',
                '/key'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation keysGetAllKeys
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return string[]
     */
    public function keysGetAllKeys()
    {
        list($response) = $this->keysGetAllKeysWithHttpInfo();
        return $response;
    }

    /**
     * Operation keysGetAllKeysWithHttpInfo
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of string[], HTTP status code, HTTP response headers (array of strings)
     */
    public function keysGetAllKeysWithHttpInfo()
    {
        // parse inputs
        $resourcePath = "/keys";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                'string[]',
                '/keys'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, 'string[]', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation keysGetAllManifests
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return object[]
     */
    public function keysGetAllManifests()
    {
        list($response) = $this->keysGetAllManifestsWithHttpInfo();
        return $response;
    }

    /**
     * Operation keysGetAllManifestsWithHttpInfo
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function keysGetAllManifestsWithHttpInfo()
    {
        // parse inputs
        $resourcePath = "/manifests";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                'object[]',
                '/manifests'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, 'object[]', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'object[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation keysGetDependents
     *
     * @param string $key_path  (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return object
     */
    public function keysGetDependents($key_path)
    {
        list($response) = $this->keysGetDependentsWithHttpInfo($key_path);
        return $response;
    }

    /**
     * Operation keysGetDependentsWithHttpInfo
     *
     * @param string $key_path  (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function keysGetDependentsWithHttpInfo($key_path)
    {
        // verify the required parameter 'key_path' is set
        if ($key_path === null) {
            throw new \InvalidArgumentException('Missing the required parameter $key_path when calling keysGetDependents');
        }
        // parse inputs
        $resourcePath = "/dependent";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($key_path !== null) {
            $queryParams['keyPath'] = $this->apiClient->getSerializer()->toQueryValue($key_path);
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                'object',
                '/dependent'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, 'object', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'object', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation keysGetKey
     *
     * @param string $key_path  (required)
     * @param string $revision  (optional)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return object
     */
    public function keysGetKey($key_path, $revision = null)
    {
        list($response) = $this->keysGetKeyWithHttpInfo($key_path, $revision);
        return $response;
    }

    /**
     * Operation keysGetKeyWithHttpInfo
     *
     * @param string $key_path  (required)
     * @param string $revision  (optional)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function keysGetKeyWithHttpInfo($key_path, $revision = null)
    {
        // verify the required parameter 'key_path' is set
        if ($key_path === null) {
            throw new \InvalidArgumentException('Missing the required parameter $key_path when calling keysGetKey');
        }
        // parse inputs
        $resourcePath = "/key";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($key_path !== null) {
            $queryParams['keyPath'] = $this->apiClient->getSerializer()->toQueryValue($key_path);
        }
        // query params
        if ($revision !== null) {
            $queryParams['revision'] = $this->apiClient->getSerializer()->toQueryValue($revision);
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                'object',
                '/key'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, 'object', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'object', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation keysGetKeyRevisionHistory
     *
     * @param string $key_path  (required)
     * @param string $since  (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return object[]
     */
    public function keysGetKeyRevisionHistory($key_path, $since)
    {
        list($response) = $this->keysGetKeyRevisionHistoryWithHttpInfo($key_path, $since);
        return $response;
    }

    /**
     * Operation keysGetKeyRevisionHistoryWithHttpInfo
     *
     * @param string $key_path  (required)
     * @param string $since  (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function keysGetKeyRevisionHistoryWithHttpInfo($key_path, $since)
    {
        // verify the required parameter 'key_path' is set
        if ($key_path === null) {
            throw new \InvalidArgumentException('Missing the required parameter $key_path when calling keysGetKeyRevisionHistory');
        }
        // verify the required parameter 'since' is set
        if ($since === null) {
            throw new \InvalidArgumentException('Missing the required parameter $since when calling keysGetKeyRevisionHistory');
        }
        // parse inputs
        $resourcePath = "/revision-history";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($key_path !== null) {
            $queryParams['keyPath'] = $this->apiClient->getSerializer()->toQueryValue($key_path);
        }
        // query params
        if ($since !== null) {
            $queryParams['since'] = $this->apiClient->getSerializer()->toQueryValue($since);
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                'object[]',
                '/revision-history'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, 'object[]', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'object[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation keysGetManifest
     *
     * @param string $key_path  (required)
     * @param string $revision  (optional)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return object
     */
    public function keysGetManifest($key_path, $revision = null)
    {
        list($response) = $this->keysGetManifestWithHttpInfo($key_path, $revision);
        return $response;
    }

    /**
     * Operation keysGetManifestWithHttpInfo
     *
     * @param string $key_path  (required)
     * @param string $revision  (optional)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function keysGetManifestWithHttpInfo($key_path, $revision = null)
    {
        // verify the required parameter 'key_path' is set
        if ($key_path === null) {
            throw new \InvalidArgumentException('Missing the required parameter $key_path when calling keysGetManifest');
        }
        // parse inputs
        $resourcePath = "/manifest";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($key_path !== null) {
            $queryParams['keyPath'] = $this->apiClient->getSerializer()->toQueryValue($key_path);
        }
        // query params
        if ($revision !== null) {
            $queryParams['revision'] = $this->apiClient->getSerializer()->toQueryValue($revision);
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                'object',
                '/manifest'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, 'object', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'object', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation keysGetRevision
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return string
     */
    public function keysGetRevision()
    {
        list($response) = $this->keysGetRevisionWithHttpInfo();
        return $response;
    }

    /**
     * Operation keysGetRevisionWithHttpInfo
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function keysGetRevisionWithHttpInfo()
    {
        // parse inputs
        $resourcePath = "/revision";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['text/html']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                'string',
                '/revision'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation keysUpdateKey
     *
     * @param string $key_path  (required)
     * @param string $author_name  (required)
     * @param string $author_email  (required)
     * @param \Swagger\Client\Model\KeyUpdateModel $value  (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return string
     */
    public function keysUpdateKey($key_path, $author_name, $author_email, $value)
    {
        list($response) = $this->keysUpdateKeyWithHttpInfo($key_path, $author_name, $author_email, $value);
        return $response;
    }

    /**
     * Operation keysUpdateKeyWithHttpInfo
     *
     * @param string $key_path  (required)
     * @param string $author_name  (required)
     * @param string $author_email  (required)
     * @param \Swagger\Client\Model\KeyUpdateModel $value  (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function keysUpdateKeyWithHttpInfo($key_path, $author_name, $author_email, $value)
    {
        // verify the required parameter 'key_path' is set
        if ($key_path === null) {
            throw new \InvalidArgumentException('Missing the required parameter $key_path when calling keysUpdateKey');
        }
        // verify the required parameter 'author_name' is set
        if ($author_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $author_name when calling keysUpdateKey');
        }
        // verify the required parameter 'author_email' is set
        if ($author_email === null) {
            throw new \InvalidArgumentException('Missing the required parameter $author_email when calling keysUpdateKey');
        }
        // verify the required parameter 'value' is set
        if ($value === null) {
            throw new \InvalidArgumentException('Missing the required parameter $value when calling keysUpdateKey');
        }
        // parse inputs
        $resourcePath = "/key";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['text/html']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($key_path !== null) {
            $queryParams['keyPath'] = $this->apiClient->getSerializer()->toQueryValue($key_path);
        }
        // query params
        if ($author_name !== null) {
            $queryParams['author.name'] = $this->apiClient->getSerializer()->toQueryValue($author_name);
        }
        // query params
        if ($author_email !== null) {
            $queryParams['author.email'] = $this->apiClient->getSerializer()->toQueryValue($author_email);
        }
        // body params
        $_tempBody = null;
        if (isset($value)) {
            $_tempBody = $value;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                'string',
                '/key'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
