<?php
/**
 * KeysApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Authoring API
 *
 * API used to query and manipulate Tweek data in git
 *
 * OpenAPI spec version: 0.2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * KeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KeysApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for keysDeleteKey
     *
     * .
     *
     */
    public function testKeysDeleteKey()
    {
    }

    /**
     * Test case for keysGetAllKeys
     *
     * .
     *
     */
    public function testKeysGetAllKeys()
    {
    }

    /**
     * Test case for keysGetAllManifests
     *
     * .
     *
     */
    public function testKeysGetAllManifests()
    {
    }

    /**
     * Test case for keysGetDependents
     *
     * .
     *
     */
    public function testKeysGetDependents()
    {
    }

    /**
     * Test case for keysGetKey
     *
     * .
     *
     */
    public function testKeysGetKey()
    {
    }

    /**
     * Test case for keysGetKeyRevisionHistory
     *
     * .
     *
     */
    public function testKeysGetKeyRevisionHistory()
    {
    }

    /**
     * Test case for keysGetManifest
     *
     * .
     *
     */
    public function testKeysGetManifest()
    {
    }

    /**
     * Test case for keysGetRevision
     *
     * .
     *
     */
    public function testKeysGetRevision()
    {
    }

    /**
     * Test case for keysUpdateKey
     *
     * .
     *
     */
    public function testKeysUpdateKey()
    {
    }
}
