<?php
/**
 * KeysApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Authoring API
 *
 * API used to query and manipulate Tweek data in git
 *
 * OpenAPI spec version: 0.2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * KeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KeysApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteKey
     *
     * .
     *
     */
    public function testDeleteKey()
    {
    }

    /**
     * Test case for listKeys
     *
     * .
     *
     */
    public function testListKeys()
    {
    }

    /**
     * Test case for listManifests
     *
     * .
     *
     */
    public function testListManifests()
    {
    }

    /**
     * Test case for getDependents
     *
     * .
     *
     */
    public function testGetDependents()
    {
    }

    /**
     * Test case for getKey
     *
     * .
     *
     */
    public function testGetKey()
    {
    }

    /**
     * Test case for getKeyRevisionHistory
     *
     * .
     *
     */
    public function testGetKeyRevisionHistory()
    {
    }

    /**
     * Test case for getManifest
     *
     * .
     *
     */
    public function testGetManifest()
    {
    }

    /**
     * Test case for getRevision
     *
     * .
     *
     */
    public function testGetRevision()
    {
    }

    /**
     * Test case for updateKey
     *
     * .
     *
     */
    public function testUpdateKey()
    {
    }
}
